// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrwHA8p1oJRD5d7VMrhZh2GsS7S9BRGVI',
    appId: '1:69133720222:web:f2fc72fbe16d5d8f2f798f',
    messagingSenderId: '69133720222',
    projectId: 'gestion-etudiant-7bfc1',
    authDomain: 'gestion-etudiant-7bfc1.firebaseapp.com',
    storageBucket: 'gestion-etudiant-7bfc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FSrSznOdbojsQDrQDMauJONy2q38Em8',
    appId: '1:69133720222:android:3259e860c050d2c62f798f',
    messagingSenderId: '69133720222',
    projectId: 'gestion-etudiant-7bfc1',
    storageBucket: 'gestion-etudiant-7bfc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-5Xvwmw-zjEVIBfBbbwTobH9WrIhqGHE',
    appId: '1:69133720222:ios:4f2f87a02d5023092f798f',
    messagingSenderId: '69133720222',
    projectId: 'gestion-etudiant-7bfc1',
    storageBucket: 'gestion-etudiant-7bfc1.firebasestorage.app',
    iosClientId: '69133720222-hqo9gihjodnmq7vb0kfnli4veqobr8s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-5Xvwmw-zjEVIBfBbbwTobH9WrIhqGHE',
    appId: '1:69133720222:ios:4f2f87a02d5023092f798f',
    messagingSenderId: '69133720222',
    projectId: 'gestion-etudiant-7bfc1',
    storageBucket: 'gestion-etudiant-7bfc1.firebasestorage.app',
    iosClientId: '69133720222-hqo9gihjodnmq7vb0kfnli4veqobr8s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrwHA8p1oJRD5d7VMrhZh2GsS7S9BRGVI',
    appId: '1:69133720222:web:6fb98caf20c728a62f798f',
    messagingSenderId: '69133720222',
    projectId: 'gestion-etudiant-7bfc1',
    authDomain: 'gestion-etudiant-7bfc1.firebaseapp.com',
    storageBucket: 'gestion-etudiant-7bfc1.firebasestorage.app',
  );
}
